### ISSUE TITLE
Minimize the requirements.txt

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/embedders#6]
I think the current state of the requirements.txt is too specific in it's versions. We could probably emit the "==" version specifications and specify them with ">=" or leave the version out completely.

Inspiration: requirements from the sentence-transformer library
https://github.com/UKPLab/sentence-transformers/blob/master/requirements.txt

**Comment by jhoetter** [comment]
fixed, thanks Mo! :-)
